apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark-operator
spec:
  type: Python
  mode: cluster
  image: "docker.io/bitnami/spark:3.5"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.5.1.jar"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    memory: "512m"
    serviceAccount: spark
  executor:
    cores: 0.1
    instances: 2
    memory: "512m"
